all:
  children:
    localhost:
      hosts:
        127.0.0.1:
          ansible_connection: local
  vars:
    ansible_user: ansible

#    switches:
#      hosts:
#    rans:
#      hosts:
#        10.64.45.22:
#          xx-name: bp2
