---
{{- if .Values.multus.create }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-net1
spec:
  config: '{ 
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": {{- cat .Values.multus.hostInterface | nospace | quote }},
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.ipadd "/" .Values.multus.netmask | nospace | quote }}
                }
        ],
        "routes": [
                {
                        "dst": "172.22.10.0/24",
                        "gw": "10.0.10.1"
                }
        ]
      }
    }'
{{- end }}

