---
{{- if .Values.multus.create }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Chart.Name }}-n2-net1
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": {{- cat .Values.multus.hostInterface | nospace | quote }},
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.n2IPadd "/" .Values.multus.n2Netmask | nospace | quote }}
                }
        ],
        "routes": [
                {
                        "dst": "10.8.0.0/24",
                        "gw": "172.22.10.1"
                },
                {
                        "dst": "10.0.10.0/24",
                        "gw": "172.22.10.1"
                },
                {
                        "dst": "10.0.20.0/24",
                        "gw": "172.22.10.1"
                }
        ]
      }
    }'
{{- end }}
